### ISSUE TITLE
Exception when migrating to version 1.1.0

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-Rest-Source-Auth#18]
```
2019-06-07 16:17:21.788  INFO 1 --- [           main] liquibase.executor.jvm.JdbcExecutor      : CREATE SEQUENCE public.hibernate_sequence START WITH 1000 INCREMENT BY 50
2019-06-07 16:17:21.954 ERROR 1 --- [           main] liquibase.changelog.ChangeSet            : Change Set db/changelog/changes/00000000000000_initial_schema.xml::00000000000000::nivethika@thehyve.nl failed.  Error: ERROR: relation "hibernate_sequence" already exists [Failed SQL: CREATE SEQUENCE public.hibernate_sequence START WITH 1000 INCREMENT BY 50]
2019-06-07 16:17:21.994  INFO 1 --- [           main] l.lockservice.StandardLockService        : Successfully released change log lock
2019-06-07 16:17:22.023  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set db/changelog/changes/00000000000000_initial_schema.xml::00000000000000::nivethika@thehyve.nl:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "hibernate_sequence" already exists [Failed SQL: CREATE SEQUENCE public.hibernate_sequence START WITH 1000 INCREMENT BY 50]
2019-06-07 16:17:22.041  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-06-07 16:17:22.267  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2019-06-07 16:17:22.322  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-06-07 16:17:22.806  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-06-07 16:17:23.070 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set db/changelog/changes/00000000000000_initial_schema.xml::00000000000000::nivethika@thehyve.nl:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "hibernate_sequence" already exists [Failed SQL: CREATE SEQUENCE public.hibernate_sequence START WITH 1000 INCREMENT BY 50]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:307) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105) ~[spring-context-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.radarbase.authorizer.RadarRestSourceAuthorizerApplication.main(RadarRestSourceAuthorizerApplication.java:44) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app.jar:na]
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set db/changelog/changes/00000000000000_initial_schema.xml::00000000000000::nivethika@thehyve.nl:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "hibernate_sequence" already exists [Failed SQL: CREATE SEQUENCE public.hibernate_sequence START WITH 1000 INCREMENT BY 50]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637) ~[liquibase-core-3.6.3.jar!/:na]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53) ~[liquibase-core-3.6.3.jar!/:na]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83) ~[liquibase-core-3.6.3.jar!/:na]
	at liquibase.Liquibase.update(Liquibase.java:202) ~[liquibase-core-3.6.3.jar!/:na]
	at liquibase.Liquibase.update(Liquibase.java:179) ~[liquibase-core-3.6.3.jar!/:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:353) ~[liquibase-core-3.6.3.jar!/:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:305) ~[liquibase-core-3.6.3.jar!/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1821) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1758) ~[spring-beans-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	... 26 common frames omitted
Caused by: liquibase.exception.DatabaseException: ERROR: relation "hibernate_sequence" already exists [Failed SQL: CREATE SEQUENCE public.hibernate_sequence START WITH 1000 INCREMENT BY 50]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356) ~[liquibase-core-3.6.3.jar!/:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57) ~[liquibase-core-3.6.3.jar!/:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125) ~[liquibase-core-3.6.3.jar!/:na]
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229) ~[liquibase-core-3.6.3.jar!/:na]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211) ~[liquibase-core-3.6.3.jar!/:na]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600) ~[liquibase-core-3.6.3.jar!/:na]
	... 34 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "hibernate_sequence" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440) ~[postgresql-42.2.5.jar!/:42.2.5]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183) ~[postgresql-42.2.5.jar!/:42.2.5]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308) ~[postgresql-42.2.5.jar!/:42.2.5]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.5.jar!/:42.2.5]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.5.jar!/:42.2.5]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307) ~[postgresql-42.2.5.jar!/:42.2.5]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293) ~[postgresql-42.2.5.jar!/:42.2.5]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270) ~[postgresql-42.2.5.jar!/:42.2.5]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266) ~[postgresql-42.2.5.jar!/:42.2.5]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[HikariCP-3.2.0.jar!/:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-3.2.0.jar!/:na]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352) ~[liquibase-core-3.6.3.jar!/:na]
	... 39 common frames omitted
```

**Comment by yatharthranjan** [comment]
Probably needs to add NO EXISTS in the liquibase changeset -- `CREATE SEQUENCE IF NOT EXISTS`

**Comment by yatharthranjan** [comment]
In Liquibase we may need to use a pre conditions check with `<sequenceExists>` as mentioned here -- https://www.liquibase.org/documentation/preconditions.html

**Comment by yatharthranjan** [comment]
AS stated in #21, use the following procedure to fix the issue

```shell
docker-compose exec radarbase-postgresql /bin/sh
/ # psql -U radarbase restsourceauthorizer 
restsourceauthorizer=# \dt
                 List of relations
 Schema |         Name          | Type  |   Owner   
--------+-----------------------+-------+-----------
 public | databasechangelog     | table | radarbase
 public | databasechangeloglock | table | radarbase
 public | rest_source_user      | table | radarbase
(3 rows)
restsourceauthorizer-# select * from databasechangelog;
restsourceauthorizer=# select * from databasechangelog;
       id       |        author        |                                filename                                 |        dateexecuted        | orderexecuted | exectype |               md5sum               |                                                                                                                        description                                                                                                                         | comments | tag | liquibase | contexts | labels | deployment_id 
----------------+----------------------+-------------------------------------------------------------------------+----------------------------+---------------+----------+------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+-----+-----------+----------+--------+---------------
 00000000000000 | nivethika@thehyve.nl | BOOT-INF/classes/db/changelog/changes/00000000000000_initial_schema.xml | 2019-03-15 10:16:46.099989 |             1 | EXECUTED | 7:a6235f40597a13436aa36c6d61db2269 | createSequence sequenceName=hibernate_sequence                                                                                                                                                                                                             |          |     | 3.5.4     |          |        | 2645005738
 00000000000001 | nivethika@thehyve.nl | BOOT-INF/classes/db/changelog/changes/00000000000000_initial_schema.xml | 2019-03-15 10:16:46.501098 |             2 | EXECUTED | 7:7017a75f4e656fc266fd69b3200f1601 | createTable tableName=rest_source_user; createIndex indexName=idx_rest_source_user_id, tableName=rest_source_user; createIndex indexName=idx_rest_source_user_external_id, tableName=rest_source_user; createIndex indexName=idx_rest_source_user_sourc... |          |     | 3.5.4     |          |        | 2645005738
(2 rows)

restsourceauthorizer=# update databasechangelog set filename = replace(filename, 'BOOT-INF/classes/db/changelog/changes/00000000000000_initial_schema.xml', 'db/changelog/changes/00000000000000_initial_schema.xml');
UPDATE 2
restsourceauthorizer=# select * from databasechangelog;
       id       |        author        |                        filename                        |        dateexecuted        | orderexecuted | exectype |               md5sum               |                                                                                                                        description                                                                                                                         | comments | tag | liquibase | contexts | labels | deployment_id 
----------------+----------------------+--------------------------------------------------------+----------------------------+---------------+----------+------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+-----+-----------+----------+--------+---------------
 00000000000000 | nivethika@thehyve.nl | db/changelog/changes/00000000000000_initial_schema.xml | 2019-03-15 10:16:46.099989 |             1 | EXECUTED | 7:a6235f40597a13436aa36c6d61db2269 | createSequence sequenceName=hibernate_sequence                                                                                                                                                                                                             |          |     | 3.5.4     |          |        | 2645005738
 00000000000001 | nivethika@thehyve.nl | db/changelog/changes/00000000000000_initial_schema.xml | 2019-03-15 10:16:46.501098 |             2 | EXECUTED | 7:7017a75f4e656fc266fd69b3200f1601 | createTable tableName=rest_source_user; createIndex indexName=idx_rest_source_user_id, tableName=rest_source_user; createIndex indexName=idx_rest_source_user_external_id, tableName=rest_source_user; createIndex indexName=idx_rest_source_user_sourc... |          |     | 3.5.4     |          |        | 2645005738
(2 rows)

restsourceauthorizer=# \q
/ # exit

```
This will fix the inconsistencies in the filename.
Now you can change to `radar-rest-authorizer-backend:1.1.0`
then restart the container

 bin/radar-docker up -d radar-rest-sources-backend
